Repository MattHillWakatipu/Momotaro, pull requests merged in 2021-10, with the labels that each got.

#150 Add KijoMomiji (Boss 2)
  Content/Assets/Sprites/Enemies/KijoMomiji/FanDance/Fan_Dance.uasset
  Content/Assets/Sprites/Enemies/KijoMomiji/FanDance/Fan_Dance1.uasset
  Content/Assets/Sprites/Enemies/KijoMomiji/FanDance/Fan_Dance1_Sprite.uasset
  Content/Assets/Sprites/Enemies/KijoMomiji/FanDance/Fan_Dance2.uasset
  Content/Assets/Sprites/Enemies/KijoMomiji/FanDance/Fan_Dance2_Sprite.uasset
  Content/Assets/Sprites/Enemies/KijoMomiji/FanDance/Fan_Dance3.uasset
  Content/Assets/Sprites/Enemies/KijoMomiji/FanDance/Fan_Dance3_Sprite.uasset
  Content/Assets/Sprites/Enemies/KijoMomiji/FanDance/Fan_Dance4.uasset
  Content/Assets/Sprites/Enemies/KijoMomiji/FanDance/Fan_Dance4_Sprite.uasset
  Content/Assets/Sprites/Enemies/KijoMomiji/FanDance/Fan_Dance5.uasset
  Content/Assets/Sprites/Enemies/KijoMomiji/FanDance/Fan_Dance5_Sprite.uasset
  Content/Assets/Sprites/Enemies/KijoMomiji/FanDance/Fan_Dance6.uasset
  Content/Assets/Sprites/Enemies/KijoMomiji/FanDance/Fan_Dance6_Sprite.uasset
  Content/Assets/Sprites/Enemies/KijoMomiji/FanDance/Fan_Dance7.uasset
  Content/Assets/Sprites/Enemies/KijoMomiji/FanDance/Fan_Dance7_Sprite.uasset
  Content/Assets/Sprites/Enemies/KijoMomiji/Idle/Idle.uasset
  Content/Assets/Sprites/Enemies/KijoMomiji/Idle/Idle1.uasset
  Content/Assets/Sprites/Enemies/KijoMomiji/Idle/Idle1_Sprite.uasset
  Content/Assets/Sprites/Enemies/KijoMomiji/Idle/Idle2.uasset
  Content/Assets/Sprites/Enemies/KijoMomiji/Idle/Idle2_Sprite.uasset
  Content/Assets/Sprites/Enemies/KijoMomiji/Idle/Idle3.uasset
  Content/Assets/Sprites/Enemies/KijoMomiji/Idle/Idle3_Sprite.uasset
  Content/Assets/Sprites/Enemies/KijoMomiji/Idle/Idle4.uasset
  Content/Assets/Sprites/Enemies/KijoMomiji/Idle/Idle4_Sprite.uasset
  Content/Assets/Sprites/Enemies/KijoMomiji/Idle/Idle5.uasset
  Content/Assets/Sprites/Enemies/KijoMomiji/Idle/Idle5_Sprite.uasset
  Content/Assets/Sprites/Enemies/KijoMomiji/Idle/Idle6.uasset
  Content/Assets/Sprites/Enemies/KijoMomiji/Idle/Idle6_Sprite.uasset
  Content/Assets/Sprites/Enemies/KijoMomiji/Idle/Idle7.uasset
  Content/Assets/Sprites/Enemies/KijoMomiji/Idle/Idle7_Sprite.uasset
  Content/Assets/Sprites/Enemies/KijoMomiji/RedMaple/Red_Maple.uasset
  Content/Assets/Sprites/Enemies/KijoMomiji/RedMaple/Red_Maple1.uasset
  Content/Assets/Sprites/Enemies/KijoMomiji/RedMaple/Red_Maple1_Sprite.uasset
  Content/Assets/Sprites/Enemies/KijoMomiji/RedMaple/Red_Maple2.uasset
  Content/Assets/Sprites/Enemies/KijoMomiji/RedMaple/Red_Maple2_Sprite.uasset
  Content/Assets/Sprites/Enemies/KijoMomiji/RedMaple/Red_Maple3.uasset
  Content/Assets/Sprites/Enemies/KijoMomiji/RedMaple/Red_Maple3_Sprite.uasset
  Content/Assets/Sprites/Enemies/KijoMomiji/RedMaple/Red_Maple4.uasset
  Content/Assets/Sprites/Enemies/KijoMomiji/RedMaple/Red_Maple4_Sprite.uasset
  Content/Assets/Sprites/Enemies/KijoMomiji/RedMaple/Red_Maple5.uasset
  Content/Assets/Sprites/Enemies/KijoMomiji/RedMaple/Red_Maple5_Sprite.uasset
  Content/Assets/Sprites/Enemies/KijoMomiji/RedMaple/Red_Maple6.uasset
  Content/Assets/Sprites/Enemies/KijoMomiji/RedMaple/Red_Maple6_Sprite.uasset
  Content/Assets/Sprites/Enemies/KijoMomiji/RedMaple/Red_Maple7.uasset
  Content/Assets/Sprites/Enemies/KijoMomiji/RedMaple/Red_Maple7_Sprite.uasset
  Content/Assets/Sprites/Enemies/KijoMomiji/RedMaple/Red_Maple8.uasset
  Content/Assets/Sprites/Enemies/KijoMomiji/RedMaple/Red_Maple8_Sprite.uasset
  Content/Assets/Sprites/Enemies/KijoMomiji/RedMaple/Red_Maple9.uasset
  Content/Assets/Sprites/Enemies/KijoMomiji/RedMaple/Red_Maple9_Sprite.uasset
  Content/Battle/Boss2.umap
  Content/Enemy/KijoMomiji.uasset
Labels: enhancement

#152 Fixed bug #147
  Content/Game/PC_PlayerController.uasset
  Content/UI/CardWidget.uasset
  Content/UI/HUD.uasset
Labels: bug

#163 Fix logic surrounding enemy death
  Content/Enemy/AxeDemon.uasset
  Content/Enemy/EnemyBase.uasset
  Content/Enemy/Imp.uasset
  Content/Enemy/KijoMomiji.uasset
  Content/Enemy/MartialHero.uasset
  Content/Enemy/MaskedWarrior.uasset
  Content/Enemy/Tengu.uasset
  Content/Game/MacroLibrary.uasset
  Content/Game/PC_PlayerController.uasset
Labels: bug

#167 Card Displaying Merged
  Content/Battle/Battle.umap
  Content/Cards/Card.uasset
  Content/Cards/Loyalty/Barrage.uasset
  Content/Cards/Loyalty/Multi-Strike.uasset
  Content/Cards/Loyalty/Roast.uasset
  Content/Cards/Neutral/Strike.uasset
  Content/Game/PC_PlayerController.uasset
  Content/UI/CardWidget.uasset
  Content/UI/HUD.uasset
  Content/UI/Main.umap
  Content/Yokai/Yokai.uasset
Labels: bug, enhancement

#209 HUD refinements
  Content/Game/PC_PlayerController.uasset
  Content/UI/TopBar.uasset
Labels: enhancement

#219 Add deck representation
  Content/Assets/UI/Misc/CardBackDiscard.uasset
  Content/Assets/UI/Misc/CardBackDraw.uasset
  Content/Game/PC_PlayerController.uasset
  Content/UI/HUD.uasset
  Content/UI/TopBar.uasset
Labels: enhancement

#223 Fix spelling of LifeLeech
  Content/Assets/Cards/Icons/LifeLeach/LifeLeach.uasset
  Content/Assets/Cards/Icons/LifeLeech/LifeLeech.uasset
  Content/Cards/Wisdom/LifeLeach.uasset
  Content/Cards/Wisdom/LifeLeech.uasset
Labels: bug

#229 Update EnemyBase.uasset
  Content/Enemy/EnemyBase.uasset
Labels: enhancement

#236 Balancing
  Content/Battle/Demons.umap
  Content/Battle/ImpsGalore.umap
  Content/Battle/KijoMomiji.umap
  Content/Battle/MartialHero.umap
  Content/Battle/TenguMaskedWarrior.umap
  Content/Cards/Card.uasset
  Content/Cards/Courage/AokijisMight.uasset
  Content/Cards/Courage/DivineProtection.uasset
  Content/Cards/Courage/Goodbye.uasset
  Content/Cards/Courage/Harmonize.uasset
  Content/Cards/Courage/HeavenlyLight.uasset
  Content/Cards/Courage/LessWildGrowth.uasset
  Content/Cards/Courage/Reflect.uasset
  Content/Cards/Courage/Sharpen.uasset
  Content/Cards/Courage/SpiritBomb.uasset
  Content/Cards/Courage/WingsOfMight.uasset
  Content/Cards/Loyalty/AinkusFury.uasset
  Content/Cards/Loyalty/Barrage.uasset
  Content/Cards/Loyalty/Cleave.uasset
  Content/Cards/Loyalty/Multi-Strike.uasset
  Content/Cards/Loyalty/OpenWounds.uasset
  Content/Cards/Loyalty/RazorSharp.uasset
  Content/Cards/Loyalty/Roast.uasset
  Content/Cards/Loyalty/Slam.uasset
  Content/Cards/Loyalty/Strike.uasset
  Content/Cards/Loyalty/SuicidalCharge.uasset
  Content/Cards/Wisdom/Bandage.uasset
  Content/Cards/Wisdom/DealersChoice.uasset
  Content/Cards/Wisdom/GreaterGood.uasset
  Content/Cards/Wisdom/LifeLeech.uasset
  Content/Cards/Wisdom/NecessarySacrifice.uasset
  Content/Cards/Wisdom/OneWithNothing.uasset
  Content/Cards/Wisdom/Outsmart.uasset
  Content/Cards/Wisdom/Replay.uasset
  Content/Cards/Wisdom/Reset.uasset
  Content/Cards/Wisdom/ThousandNeedles.uasset
  Content/Enemy/EnemyBase.uasset
  Content/Enemy/KijoMomiji.uasset
  Content/UI/CardWidget.uasset
  Content/UI/Main.umap
  Content/Yokai/Yokai.uasset
Labels: enhancement

#243 User interface
  Content/Assets/UI/Misc/Deck_HUD.uasset
  Content/Assets/UI/Misc/Exot_HUD.uasset
  Content/Assets/UI/Misc/Setings_HUD.uasset
  Content/UI/MainMenu.uasset
  Content/UI/MasterSoundMix.uasset
  Content/UI/SettingsMenu.uasset
  Content/UI/TopBar.uasset
Labels: enhancement

#245 Last adjustments
  Content/Assets/Arrow.uasset
  Content/Assets/Cards/Gems/Epic.uasset
  Content/Assets/Cards/Gems/Rare.uasset
  Content/Assets/Cards/Gems/Uncommon.uasset
  Content/Assets/Cards/Icons/AokijisMight/AokijisMight.uasset
  Content/Assets/Cards/Icons/Barrage/Barrage.uasset
  Content/Assets/Cards/Icons/Cleave/Cleave.uasset
  Content/Assets/Cards/Icons/Goodbye.uasset
  Content/Assets/Cards/Icons/Goodbye/Goodbye.uasset
  Content/Assets/Cards/Icons/Harmonize/Harmonize.uasset
  Content/Cards/CardTypes.uasset
  Content/Cards/Courage/AokijisMight.uasset
  Content/Cards/Courage/DivineProtection.uasset
  Content/Cards/Courage/Goodbye.uasset
  Content/Cards/Courage/Harmonize.uasset
  Content/Cards/Courage/HeavenlyLight.uasset
  Content/Cards/Courage/LessWildGrowth.uasset
  Content/Cards/Courage/Reflect.uasset
  Content/Cards/Courage/Sharpen.uasset
  Content/Cards/Courage/SpiritBomb.uasset
  Content/Cards/Courage/WingsOfMight.uasset
  Content/Cards/Loyalty/AinkusFury.uasset
  Content/Cards/Loyalty/Barrage.uasset
  Content/Cards/Loyalty/OpenWounds.uasset
  Content/Cards/Loyalty/RazorSharp.uasset
  Content/Cards/Loyalty/Slam.uasset
  Content/Cards/Loyalty/SuicidalCharge.uasset
  Content/Cards/Rarities.uasset
  Content/Cards/Wisdom/Bandage.uasset
  Content/Cards/Wisdom/DealersChoice.uasset
  Content/Cards/Wisdom/GreaterGood.uasset
  Content/Cards/Wisdom/LifeLeech.uasset
  Content/Cards/Wisdom/NecessarySacrifice.uasset
  Content/Cards/Wisdom/OneWithNothing.uasset
  Content/Cards/Wisdom/Outsmart.uasset
  Content/Cards/Wisdom/Replay.uasset
  Content/Cards/Wisdom/Reset.uasset
  Content/Cards/Wisdom/ThousandNeedles.uasset
  Content/Game/PC_PlayerController.uasset
  Content/UI/Arrow.uasset
  Content/UI/CardWidget.uasset
  Content/UI/Main.umap
  Content/Yokai/Ainku.uasset
  Content/Yokai/Yokai.uasset
Labels: enhancement

#247 Update KijoMomiji.uasset
  Content/Enemy/KijoMomiji.uasset
Labels: enhancement
