Repository MattHillWakatipu/Momotaro, pull requests merged in 2021-09, with the labels that each got.

#68 Add placeholder models for Enemy and Ainku
  Config/DefaultEditor.ini
  Content/Assets/Ainku/AnimatedDog.uasset
  Content/Assets/Ainku/Image_0.uasset
  Content/Assets/Ainku/Image_0_Mat.uasset
  Content/Assets/Ainku/Material_0.uasset
  Content/Assets/Ninja/MEtal_tga.uasset
  Content/Assets/Ninja/MEtal_tga_Mat.uasset
  Content/Assets/Ninja/bone2TXT_tga.uasset
  Content/Assets/Ninja/bone2TXT_tga_Mat.uasset
  Content/Assets/Ninja/cloakTXT_tga.uasset
  Content/Assets/Ninja/cloakTXT_tga_Mat.uasset
  Content/Assets/Ninja/cloak_2TXT_tga.uasset
  Content/Assets/Ninja/cloak_2TXT_tga_Mat.uasset
  Content/Assets/Ninja/ninjapose4.uasset
  Content/Assets/Ninja/samurai_armor_txt_tga.uasset
  Content/Assets/Ninja/samurai_armor_txt_tga_Mat.uasset
  Content/Battle/Battle.umap
  Content/Enemy/EnemyBase.uasset
  Content/UI/Main.umap
Labels: enhancement

#69 Battle event stubs
  Content/Enemy/EnemyHealthBar.uasset
  Content/Game/PC_PlayerController.uasset
  Content/UI/HUD.uasset
Labels: enhancement

#73 Enemy update
  Content/Battle/Battle.umap
  Content/Enemy/Action/Actionbase.uasset
  Content/Enemy/Action/Attack.uasset
  Content/Enemy/Action/Defend.uasset
  Content/Enemy/Action/PlusAttack.uasset
  Content/Enemy/EnemyBase.uasset
  Content/Enemy/FirstBoss.uasset
  Content/Enemy/FirstEnemy.uasset
  Content/UI/Main.umap
Labels: enhancement

#74 Update enemy
  Content/Enemy/Action/Actionbase.uasset
  Content/Enemy/Action/Attack.uasset
  Content/Enemy/Action/Defend.uasset
  Content/Enemy/Action/PlusAttack.uasset
  Content/Enemy/EnemyBase.uasset
  Content/Enemy/EnemyHealthBar.uasset
  Content/Enemy/FirstBoss.uasset
  Content/Enemy/FirstEnemy.uasset
Labels: enhancement

#75 Add model for FirstEnemy
  Content/Battle/Battle.umap
  Content/Enemy/EnemyBase.uasset
  Content/Enemy/FirstBoss.uasset
  Content/Enemy/FirstEnemy.uasset
Labels: enhancement

#78 Pause menu fixes
  Content/Game/PC_PlayerController.uasset
  Content/UI/PauseMenu.uasset
Labels: bug

#80 Carried over changes to Player Controller
  Content/Game/PC_PlayerController.uasset
  Content/Player+Yokai/Dog.uasset
  Content/Player+Yokai/Yokai.uasset
  Content/Yokai/Yokai.uasset
Labels: enhancement

#90 Battle UI
  Content/Battle/Battle.umap
  Content/Battle/BossBattle.umap
  Content/CardBlueprints/CardWidget.uasset
  Content/CardBlueprints/Hand.uasset
  Content/Enemy/EnemyBase.uasset
  Content/Enemy/FirstBoss.uasset
  Content/Game/PC_PlayerController.uasset
  Content/UI/HUD.uasset
  Content/UI/Main.umap
  Content/Yokai/Ainku.uasset
  Content/Yokai/Yokai.uasset
Labels: bug, enhancement

#92 Actions now implemented
  Content/Battle/Battle.umap
  Content/Enemy/Action/Actionbase.uasset
  Content/Enemy/Action/Attack.uasset
  Content/Enemy/Action/Defend.uasset
  Content/Enemy/Action/PlusAttack.uasset
  Content/Enemy/Actions.uasset
  Content/Enemy/EnemyBase.uasset
  Content/Enemy/FirstBoss.uasset
  Content/Enemy/FirstEnemy.uasset
  Content/Game/PC_PlayerController.uasset
  Content/UI/Main.umap
Labels: enhancement

#99 Add functionality to disable end turn button
  Content/Cards/Courage/LessWildGrowth.uasset
  Content/Game/PC_PlayerController.uasset
  Content/UI/HUD.uasset
Labels: bug

#100 Change Yokai and Enemy to 2D Sprites
  Config/DefaultEngine.ini
  Content/Assets/Ainku/AnimatedDog.uasset
  Content/Assets/Ainku/Image_0.uasset
  Content/Assets/Ainku/Image_0_Mat.uasset
  Content/Assets/Ainku/Material_0.uasset
  Content/Assets/Ninja/MEtal_tga.uasset
  Content/Assets/Ninja/MEtal_tga_Mat.uasset
  Content/Assets/Ninja/bone2TXT_tga.uasset
  Content/Assets/Ninja/bone2TXT_tga_Mat.uasset
  Content/Assets/Ninja/cloakTXT_tga.uasset
  Content/Assets/Ninja/cloakTXT_tga_Mat.uasset
  Content/Assets/Ninja/cloak_2TXT_tga.uasset
  Content/Assets/Ninja/cloak_2TXT_tga_Mat.uasset
  Content/Assets/Ninja/ninjapose4.uasset
  Content/Assets/Ninja/samurai_armor_txt_tga.uasset
  Content/Assets/Ninja/samurai_armor_txt_tga_Mat.uasset
  Content/Assets/Sprites/Backgrounds/Woods/parallax-demon-woods-bg.uasset
  Content/Assets/Sprites/Backgrounds/Woods/parallax-demon-woods-bg_Sprite.uasset
  Content/Assets/Sprites/Backgrounds/Woods/parallax-demon-woods-close-trees.uasset
  Content/Assets/Sprites/Backgrounds/Woods/parallax-demon-woods-close-trees_Sprite.uasset
  Content/Assets/Sprites/Backgrounds/Woods/parallax-demon-woods-far-trees.uasset
  Content/Assets/Sprites/Backgrounds/Woods/parallax-demon-woods-far-trees_Sprite.uasset
  Content/Assets/Sprites/Backgrounds/Woods/parallax-demon-woods-mid-trees.uasset
  Content/Assets/Sprites/Backgrounds/Woods/parallax-demon-woods-mid-trees_Sprite.uasset
  Content/Assets/Sprites/Enemies/Imp/ready.uasset
  Content/Assets/Sprites/Enemies/Imp/ready_1.uasset
  Content/Assets/Sprites/Enemies/Imp/ready_1_Sprite.uasset
  Content/Assets/Sprites/Enemies/Imp/ready_2.uasset
  Content/Assets/Sprites/Enemies/Imp/ready_2_Sprite.uasset
  Content/Assets/Sprites/Enemies/Imp/ready_3.uasset
  Content/Assets/Sprites/Enemies/Imp/ready_3_Sprite.uasset
  Content/Assets/Sprites/Enemies/Imp/ready_4.uasset
  Content/Assets/Sprites/Enemies/Imp/ready_4_Sprite.uasset
  Content/Assets/Sprites/Enemies/Imp/ready_5.uasset
  Content/Assets/Sprites/Enemies/Imp/ready_5_Sprite.uasset
  Content/Assets/Sprites/Enemies/Imp/ready_6.uasset
  Content/Assets/Sprites/Enemies/Imp/ready_6_Sprite.uasset
  Content/Assets/Sprites/Yokai/Hellhound/hell-hound-idle.uasset
  Content/Assets/Sprites/Yokai/Hellhound/hell-hound-idle1.uasset
  Content/Assets/Sprites/Yokai/Hellhound/hell-hound-idle_Mat.uasset
  Content/Assets/Sprites/Yokai/Hellhound/hell-hound-idle_Sprite_0.uasset
  Content/Assets/Sprites/Yokai/Hellhound/hell-hound-idle_Sprite_1.uasset
  Content/Assets/Sprites/Yokai/Hellhound/hell-hound-idle_Sprite_2.uasset
  Content/Assets/Sprites/Yokai/Hellhound/hell-hound-idle_Sprite_3.uasset
  Content/Assets/Sprites/Yokai/Hellhound/hell-hound-idle_Sprite_4.uasset
  Content/Assets/Sprites/Yokai/Hellhound/hell-hound-idle_Sprite_5.uasset
  Content/Battle/Battle.umap
  Content/Enemy/FirstEnemy.uasset
  Content/Yokai/Ainku.uasset
Labels: enhancement

#123 User interface
  Content/Assets/Fonts/MinimalPixel_v2.uasset
  Content/Assets/Fonts/MinimalPixel_v2_Font.uasset
  Content/Assets/Fonts/OptimusPrinceps.uasset
  Content/Assets/Fonts/OptimusPrinceps_Font.uasset
  Content/Assets/UI/Buttons/Button_Normal.uasset
  Content/Assets/UI/Buttons/Button_Pressed.uasset
  Content/Assets/UI/Misc/Onigiri_Mana.uasset
  Content/Fonts/OptimusPrinceps.uasset
  Content/Fonts/OptimusPrinceps_Font.uasset
  Content/Game/PC_PlayerController.uasset
  Content/UI/HUD.uasset
  Content/UI/Main.umap
  Content/UI/MainMenu.uasset
Labels: enhancement

#142 Enemy delay
  Content/Enemy/EnemyBase.uasset
  Content/Enemy/MartialHero.uasset
  Content/Game/MacroLibrary.uasset
  Content/Game/PC_PlayerController.uasset
Labels: enhancement

#146 Add checks for after spawn animation
  Content/Enemy/EnemyBase.uasset
Labels: bug
